export const ESCROW_CONTRACT_ADDRESS = process.env.REACT_APP_ESCROW_CONTRACT_ADDRESS || '0x0000000000000000000000000000000000000000';

export const ESCROW_STATUS = {
  PENDING: 'PENDING',
  FUNDED: 'FUNDED',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
} as const;

export const ESCROW_ERROR_CODES = {
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_ESCROW_ID: 'INVALID_ESCROW_ID',
  DISPUTE_ALREADY_RESOLVED: 'DISPUTE_ALREADY_RESOLVED',
} as const;
