export const BOOST_CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000'; // Substituir pelo endereço real do contrato
export const BOOST_ERROR_CODES = {
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
};

export const VISIBILITY_LEVELS = {
  LOW: 0,
  MEDIUM: 1,
  HIGH: 2,
  PREMIUM: 3,
} as const;

export const SLOT_TYPES = {
  HOMEPAGE_BANNER: 'HOMEPAGE_BANNER',
  CATEGORY_TOP: 'CATEGORY_TOP',
  SEARCH_HIGHLIGHT: 'SEARCH_HIGHLIGHT',
} as const;
