export const FOLLOW_CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000'; // To be updated with actual deployment address
export const FOLLOW_SERVICE_ERROR_CODES = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_PREFERENCES: 'INVALID_PREFERENCES',
  INVALID_NOTIFICATION_FORMAT: 'INVALID_NOTIFICATION_FORMAT',
  CONTRACT_INTERACTION_FAILED: 'CONTRACT_INTERACTION_FAILED',
};

export const NOTIFICATION_TYPES = {
  PRICE_DROP: 'PRICE_DROP',
  BACK_IN_STOCK: 'BACK_IN_STOCK',
  PROMOTION: 'PROMOTION',
  GENERAL: 'GENERAL',
} as const;

export type NotificationType = typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES];
