export const DROP_CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000'; // Replace with actual contract address

export const DROP_ERROR_CODES = {
  NOT_ACTIVE: 'DROP_NOT_ACTIVE',
  ACCESS_DENIED: 'ACCESS_DENIED',
  EXPIRED: 'DROP_EXPIRED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  ALREADY_PARTICIPATED: 'ALREADY_PARTICIPATED',
} as const;

export const DROP_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
